// <auto-generated />
using System;
using EnflorarteTopiProyecto.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnflorarteTopiProyecto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209221137_Comandas")]
    partial class Comandas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comanda_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnticipoPagoTotal")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("anticipo_total");

                    b.Property<string>("AnticipoTipo")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("anticipo_tipo");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cliente_nombre");

                    b.Property<string>("ClienteTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cliente_telefono");

                    b.Property<string>("DireccionEntrega")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion_entrega");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<string>("FotoArregloRuta")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("foto_arreglo_ruta");

                    b.Property<TimeSpan>("HoraEntrega")
                        .HasColumnType("time")
                        .HasColumnName("hora_entrega");

                    b.Property<bool>("Liquidado")
                        .HasColumnType("bit")
                        .HasColumnName("liquidado");

                    b.Property<string>("NombreArreglo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre_arreglo");

                    b.Property<decimal>("PagoEnvio")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("pago_envio");

                    b.Property<decimal>("PrecioArreglo")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("precio_arreglo");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("int")
                        .HasColumnName("repartidor_id");

                    b.Property<string>("TipoEntrega")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_entrega");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comanda", null, t =>
                        {
                            t.HasCheckConstraint("CK_Comanda_AnticipoTotal_NonNegative", "[anticipo_total] >= 0");

                            t.HasCheckConstraint("CK_Comanda_PagoEnvio_NonNegative", "[pago_envio] >= 0");

                            t.HasCheckConstraint("CK_Comanda_PrecioArreglo_NonNegative", "[precio_arreglo] >= 0");
                        });
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.Comanda", b =>
                {
                    b.HasOne("EnflorarteTopiProyecto.Models.Usuario", "RepartidorAsignado")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EnflorarteTopiProyecto.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RepartidorAsignado");

                    b.Navigation("UsuarioCreador");
                });
#pragma warning restore 612, 618
        }
    }
}
