// <auto-generated />
using System;
using EnflorarteTopiProyecto.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnflorarteTopiProyecto.Migrations.Postgres
{
    [DbContext(typeof(ApplicationDbContextPostgres))]
    partial class ApplicationDbContextPostgresModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.Arreglo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("arreglo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("FotoRuta")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("foto_ruta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("arreglo", (string)null);
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.ArregloFlor", b =>
                {
                    b.Property<int>("ArregloId")
                        .HasColumnType("integer")
                        .HasColumnName("arreglo_id");

                    b.Property<int>("FlorId")
                        .HasColumnType("integer")
                        .HasColumnName("flor_id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("ColorSeleccionado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color_seleccionado");

                    b.HasKey("ArregloId", "FlorId");

                    b.HasIndex("FlorId");

                    b.ToTable("arreglo_flor", (string)null);
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("comanda_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccesorioArreglo")
                        .HasColumnType("text");

                    b.Property<decimal>("AnticipoPagoTotal")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("anticipo_total");

                    b.Property<string>("AnticipoTipo")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("anticipo_tipo");

                    b.Property<bool>("Archivado")
                        .HasColumnType("boolean");

                    b.Property<int>("ArregloId")
                        .HasColumnType("integer")
                        .HasColumnName("arreglo_id");

                    b.Property<int>("CantidadArreglo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("cantidad_arreglo");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cliente_nombre");

                    b.Property<string>("ClienteTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cliente_telefono");

                    b.Property<string>("DireccionEntrega")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion_entrega");

                    b.Property<string>("DomicilioReferencias")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("domicilio_referencias");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<string>("FotoArregloRuta")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("HoraEntrega")
                        .HasColumnType("time")
                        .HasColumnName("hora_entrega");

                    b.Property<string>("LinkDireccion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("link_direccion");

                    b.Property<bool>("Liquidado")
                        .HasColumnType("boolean")
                        .HasColumnName("liquidado");

                    b.Property<string>("MedioDeLaSolicitud")
                        .HasColumnType("text");

                    b.Property<string>("MensajeArreglo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensaje_arreglo");

                    b.Property<string>("NombreArreglo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreReceptorEnvio")
                        .HasColumnType("text");

                    b.Property<int?>("NumeroRuta")
                        .HasColumnType("integer")
                        .HasColumnName("numero_ruta");

                    b.Property<decimal>("PagoEnvio")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("pago_envio");

                    b.Property<decimal>("PrecioArreglo")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("precio_arreglo");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("integer")
                        .HasColumnName("repartidor_id");

                    b.Property<int?>("TelefonoReceptorEnvio")
                        .HasColumnType("integer");

                    b.Property<string>("TipoEntrega")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_entrega");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ArregloId");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comanda", null, t =>
                        {
                            t.HasCheckConstraint("CK_Comanda_AnticipoTotal_NonNegative", "anticipo_total >= 0");

                            t.HasCheckConstraint("CK_Comanda_CantidadArreglo_ValidRange", "cantidad_arreglo BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Comanda_NumeroRuta_PositiveOrNull", "numero_ruta IS NULL OR numero_ruta > 0");

                            t.HasCheckConstraint("CK_Comanda_PagoEnvio_NonNegative", "pago_envio >= 0");

                            t.HasCheckConstraint("CK_Comanda_PrecioArreglo_NonNegative", "precio_arreglo >= 0");
                        });
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.ComandaFlor", b =>
                {
                    b.Property<int>("ComandaId")
                        .HasColumnType("integer")
                        .HasColumnName("comanda_id");

                    b.Property<int>("FlorId")
                        .HasColumnType("integer")
                        .HasColumnName("flor_id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("ColorSeleccionado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color_seleccionado");

                    b.HasKey("ComandaId", "FlorId");

                    b.HasIndex("FlorId");

                    b.ToTable("comanda_flor", (string)null);
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.Flor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("flor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("FotoRuta")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("foto_ruta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("flor", (string)null);
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.FlorInventarioColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("flor_inventario_color_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<int>("FlorId")
                        .HasColumnType("integer")
                        .HasColumnName("flor_id");

                    b.HasKey("Id");

                    b.HasIndex("FlorId", "Color")
                        .IsUnique();

                    b.ToTable("flor_inventario_color", (string)null);
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.ArregloFlor", b =>
                {
                    b.HasOne("EnflorarteTopiProyecto.Models.Arreglo", "Arreglo")
                        .WithMany("Flores")
                        .HasForeignKey("ArregloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnflorarteTopiProyecto.Models.Flor", "Flor")
                        .WithMany("Arreglos")
                        .HasForeignKey("FlorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arreglo");

                    b.Navigation("Flor");
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.Comanda", b =>
                {
                    b.HasOne("EnflorarteTopiProyecto.Models.Arreglo", "Arreglo")
                        .WithMany()
                        .HasForeignKey("ArregloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnflorarteTopiProyecto.Models.Usuario", "RepartidorAsignado")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("EnflorarteTopiProyecto.Models.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Arreglo");

                    b.Navigation("RepartidorAsignado");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.ComandaFlor", b =>
                {
                    b.HasOne("EnflorarteTopiProyecto.Models.Comanda", "Comanda")
                        .WithMany("Flores")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnflorarteTopiProyecto.Models.Flor", "Flor")
                        .WithMany()
                        .HasForeignKey("FlorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Flor");
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.FlorInventarioColor", b =>
                {
                    b.HasOne("EnflorarteTopiProyecto.Models.Flor", "Flor")
                        .WithMany("InventarioColores")
                        .HasForeignKey("FlorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flor");
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.Arreglo", b =>
                {
                    b.Navigation("Flores");
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.Comanda", b =>
                {
                    b.Navigation("Flores");
                });

            modelBuilder.Entity("EnflorarteTopiProyecto.Models.Flor", b =>
                {
                    b.Navigation("Arreglos");

                    b.Navigation("InventarioColores");
                });
#pragma warning restore 612, 618
        }
    }
}
